version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FILL IN"
s3_bucket = "FILL IN"
s3_prefix = "FILL IN"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

